all:
	g++ config.cpp ../../lib/librcar.a ../../3rdparty/lib/libzookeeper_mt.a -o rcar-config -std=c++11 -g -I../../3rdparty/include/ -I../../lib -L../../3rdparty/lib -L../../3rdparty/lib/x86_64-linux-gnu -L../../lib -L/usr/local/lib -Wl,-rpath ../../3rdparty/lib/x86_64-linux-gnu -lpthread 
